// All level definitions. Each level object is passed directly into useGame / createGame.
// The `config` sub-object is what the engine reads at runtime.

const SUBURBAN_SCENERY = [
  { kind: 'pasture', x: 60,   y: 60,  w: 380, h: 380, sheep: 4 },
  { kind: 'pasture', x: 60,   y: 720, w: 360, h: 340, sheep: 3 },
  { kind: 'pasture', x: 1200, y: 60,  w: 360, h: 360, sheep: 2 },
  { kind: 'pasture', x: 1260, y: 800, w: 300, h: 260, sheep: 2 },
  { kind: 'school',  x: 600,  y: 350, w: 240, h: 160 },
  { kind: 'house',   x: 200,  y: 380, w: 90,  h: 80,  hue: 14  },
  { kind: 'house',   x: 320,  y: 660, w: 100, h: 90,  hue: 200 },
  { kind: 'house',   x: 1340, y: 380, w: 90,  h: 80,  hue: 40  },
  { kind: 'house',   x: 880,  y: 760, w: 100, h: 90,  hue: 320 },
  { kind: 'bush',    x: 480,  y: 470, r: 18 },
  { kind: 'bush',    x: 520,  y: 480, r: 14 },
  { kind: 'bush',    x: 920,  y: 640, r: 16 },
  { kind: 'bush',    x: 80,   y: 580, r: 20 },
  { kind: 'bush',    x: 30,   y: 540, r: 14 },
  { kind: 'bush',    x: 1440, y: 600, r: 18 },
  { kind: 'bush',    x: 1480, y: 540, r: 14 },
  { kind: 'fern',    x: 460,  y: 520, s: 1   },
  { kind: 'fern',    x: 920,  y: 620, s: 1.2 },
  { kind: 'fern',    x: 1480, y: 660, s: 0.9 },
  { kind: 'fern',    x: 60,   y: 510, s: 1.1 },
];

const CITY_SCENERY = [
  { kind: 'pasture', x: 60,   y: 60,  w: 160, h: 380, sheep: 1 },
  { kind: 'house',   x: 200,  y: 380, w: 90,  h: 80,  hue: 14  },
  { kind: 'house',   x: 310,  y: 380, w: 90,  h: 80,  hue: 200 },
  { kind: 'house',   x: 420,  y: 380, w: 90,  h: 80,  hue: 40  },
  { kind: 'house',   x: 200,  y: 660, w: 90,  h: 80,  hue: 100 },
  { kind: 'house',   x: 310,  y: 660, w: 90,  h: 80,  hue: 200 },
  { kind: 'house',   x: 700,  y: 660, w: 100, h: 90,  hue: 40  },
  { kind: 'house',   x: 1100, y: 380, w: 90,  h: 80,  hue: 200 },
  { kind: 'house',   x: 1210, y: 380, w: 90,  h: 80,  hue: 14  },
  { kind: 'house',   x: 1300, y: 660, w: 90,  h: 80,  hue: 320 },
  { kind: 'house',   x: 1410, y: 660, w: 100, h: 90,  hue: 14  },
  { kind: 'house',   x: 1600, y: 380, w: 90,  h: 80,  hue: 200 },
  { kind: 'house',   x: 1710, y: 660, w: 90,  h: 80,  hue: 40  },
  { kind: 'bush',    x: 80,   y: 580, r: 14 },
  { kind: 'bush',    x: 920,  y: 640, r: 16 },
  { kind: 'bush',    x: 1800, y: 500, r: 18 },
];

const RURAL_SCENERY = [
  { kind: 'pasture', x: 60,   y: 60,  w: 480, h: 380, sheep: 6 },
  { kind: 'pasture', x: 60,   y: 720, w: 460, h: 340, sheep: 5 },
  { kind: 'pasture', x: 800,  y: 60,  w: 500, h: 380, sheep: 4 },
  { kind: 'pasture', x: 800,  y: 720, w: 500, h: 300, sheep: 3 },
  { kind: 'pasture', x: 1400, y: 60,  w: 400, h: 380, sheep: 3 },
  { kind: 'pasture', x: 1700, y: 720, w: 360, h: 300, sheep: 2 },
  { kind: 'bush',    x: 600,  y: 470, r: 22 },
  { kind: 'bush',    x: 640,  y: 490, r: 18 },
  { kind: 'bush',    x: 1000, y: 640, r: 20 },
  { kind: 'bush',    x: 1040, y: 620, r: 16 },
  { kind: 'bush',    x: 1800, y: 600, r: 22 },
  { kind: 'bush',    x: 1840, y: 580, r: 16 },
  { kind: 'fern',    x: 580,  y: 520, s: 1.3 },
  { kind: 'fern',    x: 1000, y: 620, s: 1.2 },
  { kind: 'fern',    x: 1840, y: 660, s: 1.1 },
  { kind: 'fern',    x: 60,   y: 510, s: 1.1 },
];

const MOUNTAIN_SCENERY = [
  { kind: 'mountain', x: 0,    y: 0,   w: 2200, h: 440 },
  { kind: 'pine',     x: 80,   y: 480, r: 20 },
  { kind: 'pine',     x: 120,  y: 470, r: 16 },
  { kind: 'pine',     x: 200,  y: 490, r: 18 },
  { kind: 'pine',     x: 340,  y: 480, r: 22 },
  { kind: 'pine',     x: 390,  y: 470, r: 14 },
  { kind: 'pine',     x: 620,  y: 490, r: 18 },
  { kind: 'pine',     x: 660,  y: 480, r: 14 },
  { kind: 'pine',     x: 820,  y: 470, r: 20 },
  { kind: 'pine',     x: 1220, y: 480, r: 18 },
  { kind: 'pine',     x: 1260, y: 460, r: 14 },
  { kind: 'pine',     x: 1720, y: 490, r: 20 },
  { kind: 'pine',     x: 1760, y: 480, r: 16 },
  { kind: 'pine',     x: 80,   y: 630, r: 16 },
  { kind: 'pine',     x: 200,  y: 650, r: 18 },
  { kind: 'pine',     x: 500,  y: 640, r: 14 },
  { kind: 'pine',     x: 820,  y: 620, r: 18 },
  { kind: 'pine',     x: 1020, y: 650, r: 20 },
  { kind: 'pine',     x: 1720, y: 620, r: 16 },
];

export const LEVELS = [
  {
    id: 'suburban',
    number: 1,
    name: 'Level 1',
    title: 'Suburban Streets',
    subtitle: 'School zones, pedestrian crossings & give-way',
    missionName: 'The School Run',
    description: 'Navigate through a quiet suburb. Watch for the school zone speed limit, stop for pedestrians at the zebra crossing, and give way correctly at the intersection.',
    themes: ['Keep Left', 'School Zone', 'Pedestrian Crossing', 'Give Way'],
    color: '#f5b81d',
    textColor: '#1a1a1a',
    bgColor: '#7fb35a',
    startName: 'MILFORD',
    destName: 'TAKAPUNA',
    worldWidth: 1600,
    startX: 140,
    finishX: 1480,
    speedLimit: 50,
    hazards: [
      { id: 'school',   x: 710,  label: 'School zone 40',       icon: 'SCH', color: '#f5b81d' },
      { id: 'ped',      x: 980,  label: 'Pedestrian crossing',  icon: 'PED', color: '#fff'    },
      { id: 'giveway',  x: 1180, label: 'Give-way intersection', icon: 'GW',  color: '#7ec8ff' },
      { id: 'finish',   x: 1480, label: 'Destination',           icon: 'FIN', color: '#7ce69a' },
    ],
    signs: [
      { kind: 'keep-left',         x: 80,   y: 660 },
      { kind: 'school-zone-start', x: 510,  y: 450 },
      { kind: 'school-zone-end',   x: 910,  y: 648 },
      { kind: 'kiwi-crossing',     x: 920,  y: 465 },
      { kind: 'give-way',          x: 1130, y: 465 },
      { kind: 'speed-50',          x: 300,  y: 465 },
      { kind: 'speed-50',          x: 1320, y: 648 },
    ],
    scenery: SUBURBAN_SCENERY,
    objectives: [
      { id: 'left',    label: 'Keep to the left lane'      },
      { id: 'school',  label: 'Slow to 40 in school zone'  },
      { id: 'ped',     label: 'Stop for pedestrians'       },
      { id: 'giveway', label: 'Give way at intersection'   },
      { id: 'finish',  label: 'Reach the finish line'      },
    ],
    config: {
      schoolZone: { x1: 540, x2: 880 },
      pedX: 980,
      sideX: 1180,
    },
  },

  {
    id: 'city',
    number: 2,
    name: 'Level 2',
    title: 'City Commute',
    subtitle: 'Roundabouts, pedestrian crossings & urban intersections',
    missionName: 'City Loop',
    description: 'Navigate busy city streets. Slow down at the roundabout, stop for pedestrians, and give way correctly at the T-intersection.',
    themes: ['Roundabout Rules', 'Urban Driving', 'Pedestrian Crossing', 'Give Way'],
    color: '#a78bfa',
    textColor: '#fff',
    bgColor: '#7fb35a',
    startName: 'CBD',
    destName: 'NEWMARKET',
    worldWidth: 1900,
    startX: 140,
    finishX: 1800,
    speedLimit: 50,
    hazards: [
      { id: 'ped',        x: 550,  label: 'Pedestrian crossing',   icon: 'PED', color: '#fff'    },
      { id: 'roundabout', x: 1000, label: 'Roundabout — slow',     icon: 'RAB', color: '#a78bfa' },
      { id: 'giveway',    x: 1500, label: 'Give-way intersection',  icon: 'GW',  color: '#7ec8ff' },
      { id: 'finish',     x: 1800, label: 'Destination',            icon: 'FIN', color: '#7ce69a' },
    ],
    signs: [
      { kind: 'keep-left',          x: 80,   y: 660 },
      { kind: 'speed-50',           x: 300,  y: 465 },
      { kind: 'kiwi-crossing',      x: 490,  y: 465 },
      { kind: 'roundabout-warning', x: 840,  y: 465 },
      { kind: 'give-way',           x: 921,  y: 465 },
      { kind: 'give-way',           x: 1450, y: 465 },
      { kind: 'speed-50',           x: 1700, y: 465 },
    ],
    scenery: CITY_SCENERY,
    objectives: [
      { id: 'left',       label: 'Keep to the left lane'          },
      { id: 'ped',        label: 'Stop for pedestrians'           },
      { id: 'roundabout', label: 'Slow for roundabout (≤40 km/h)' },
      { id: 'roundabout-giveway', label: 'Give way in roundabout' },
      { id: 'giveway',    label: 'Give way at intersection'       },
      { id: 'finish',     label: 'Reach the finish line'          },
    ],
    config: {
      pedX: 550,
      roundaboutX: 1000,
      sideX: 1500,
    },
  },

  {
    id: 'rural',
    number: 3,
    name: 'Level 3',
    title: 'Rural Road Trip',
    subtitle: 'Railway crossings, one-lane bridges & gravel roads',
    missionName: 'Country Run',
    description: 'Head out into the countryside. Slow right down on the gravel road, come to a stop at the railway crossing, and cross the one-lane bridge with care.',
    themes: ['Gravel Road', 'Railway Crossing', 'One-Lane Bridge', 'Open Road'],
    color: '#c4a35a',
    textColor: '#1a1a1a',
    bgColor: '#7fb35a',
    startName: 'HAMILTON',
    destName: 'CAMBRIDGE',
    worldWidth: 2100,
    startX: 140,
    finishX: 2000,
    speedLimit: 100,
    hazards: [
      { id: 'gravel', x: 700,  label: 'Gravel — slow to 60',    icon: 'GRV', color: '#c4a35a' },
      { id: 'rail',   x: 900,  label: 'Railway crossing — stop', icon: 'RWY', color: '#ff6b6b' },
      { id: 'bridge', x: 1400, label: 'One-lane bridge',         icon: 'BRG', color: '#7ec8ff' },
      { id: 'finish', x: 2000, label: 'Destination',             icon: 'FIN', color: '#7ce69a' },
    ],
    signs: [
      { kind: 'keep-left',        x: 80,   y: 660 },
      { kind: 'speed-100',        x: 300,  y: 465 },
      { kind: 'loose-chippings',  x: 480,  y: 465 },
      { kind: 'railway-crossing', x: 780,  y: 465 },
      { kind: 'one-lane-bridge',  x: 1270, y: 465 },
      { kind: 'speed-100',        x: 1650, y: 465 },
    ],
    scenery: RURAL_SCENERY,
    objectives: [
      { id: 'left',   label: 'Keep to the left lane'           },
      { id: 'gravel', label: 'Slow on gravel road (≤60 km/h)'  },
      { id: 'rail',   label: 'Stop at railway crossing'        },
      { id: 'bridge', label: 'Cross one-lane bridge (≤40 km/h)'},
      { id: 'finish', label: 'Reach the finish line'           },
    ],
    config: {
      gravelZone: { x1: 580, x2: 980 },
      railX: 900,
      bridgeX: 1400,
    },
  },

  {
    id: 'mountain',
    number: 4,
    name: 'Level 4',
    title: 'Mountain Pass',
    subtitle: 'Icy roads, bridges, rail crossings & give-way — the full test',
    missionName: 'Summit Challenge',
    description: 'A comprehensive mountain challenge combining everything you have learned. Slow on the icy road, cross the bridge safely, stop at the rail crossing, and give way at the intersection.',
    themes: ['Icy Road', 'Mountain Bridge', 'Railway Crossing', 'Give Way'],
    color: '#7ec8ff',
    textColor: '#1a1a1a',
    bgColor: '#8ca898',
    startName: 'OHAKUNE',
    destName: 'SUMMIT',
    worldWidth: 2200,
    startX: 140,
    finishX: 2100,
    speedLimit: 100,
    hazards: [
      { id: 'school',  x: 700,  label: 'Icy road — slow to 30',  icon: 'ICE', color: '#7ec8ff' },
      { id: 'bridge',  x: 1100, label: 'Mountain bridge',         icon: 'BRG', color: '#7ec8ff' },
      { id: 'rail',    x: 1550, label: 'Railway crossing — stop', icon: 'RWY', color: '#ff6b6b' },
      { id: 'giveway', x: 1820, label: 'Give-way intersection',   icon: 'GW',  color: '#7ec8ff' },
      { id: 'finish',  x: 2100, label: 'Summit',                  icon: 'FIN', color: '#7ce69a' },
    ],
    signs: [
      { kind: 'keep-left',        x: 80,   y: 660 },
      { kind: 'speed-100',        x: 300,  y: 465 },
      { kind: 'slippery-surface', x: 510,  y: 465 },
      { kind: 'speed-30',         x: 565,  y: 465 },
      { kind: 'speed-100',        x: 910,  y: 648 },
      { kind: 'one-lane-bridge',  x: 970,  y: 465 },
      { kind: 'railway-crossing', x: 1420, y: 465 },
      { kind: 'give-way',         x: 1770, y: 465 },
      { kind: 'speed-100',        x: 1970, y: 465 },
    ],
    scenery: MOUNTAIN_SCENERY,
    objectives: [
      { id: 'left',    label: 'Keep to the left lane'            },
      { id: 'school',  label: 'Slow to 30 on icy road'           },
      { id: 'bridge',  label: 'Cross mountain bridge (≤40 km/h)' },
      { id: 'rail',    label: 'Stop at railway crossing'         },
      { id: 'giveway', label: 'Give way at intersection'         },
      { id: 'finish',  label: 'Reach the summit'                 },
    ],
    config: {
      schoolZone: { x1: 580, x2: 870 },
      bridgeX: 1100,
      railX: 1550,
      sideX: 1820,
    },
  },
];
